name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
        working-directory: frontend/flutter_neuropilot
      - run: |
          flutter build web --release \
            --dart-define=API_BASE_URL=/api \
            --dart-define=FIREBASE_API_KEY=AIzaSyAJLKL_cROVl7fOJsO1oZuOKDhjzf36O8w \
            --dart-define=FIREBASE_APP_ID=1:848026269314:web:496ec795532a3b8363269b \
            --dart-define=FIREBASE_MESSAGING_SENDER_ID=848026269314 \
            --dart-define=FIREBASE_PROJECT_ID=neuropilot-23fb5 \
            --dart-define=FIREBASE_AUTH_DOMAIN=neuropilot-23fb5.firebaseapp.com \
            --dart-define=FIREBASE_STORAGE_BUCKET=neuropilot-23fb5.firebasestorage.app
        working-directory: frontend/flutter_neuropilot
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEUROPILOT_23FB5 }}"
          projectId: "neuropilot-23fb5"
          channelId: live
          entryPoint: .
